before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: onspaceship
      name: ship
    folder: Formula
    homepage: https://spaceship.run
    description: Launch your code with one click
    license: MIT
    install: bin.install "ship"
